font_family DejaVu Sans Mono
font_size 10.5
scrollback_lines 0
remember_window_size no
window_padding_width 0
window_margin_width 0
initial_window_width 80c
initial_window_height 24c
hide_window_decorations yes
shell_integration disabled
linux_display_server wayland
