#!/usr/bin/env python3
"""Exercise a real Linux window, verified loopback SSH, and interactive TUIs.

Run as an ordinary user under Xvfb. Only Python's standard library is imported;
external programs are OpenSSH, xdotool, xwd, Neovim, fzf, and tmux. The daemon,
keys, authorized_keys, known_hosts, and tmux socket belong to one temporary
fixture. No existing SSH configuration, account, or service is modified.

Host trust comes from the host public key generated by this fixture, never from
ssh-keyscan or disabled verification. See https://man.openbsd.org/ssh_config
and https://man.openbsd.org/sshd for the pinned-key and foreground-daemon flags.
"""

import argparse
import json
import os
from pathlib import Path
import pwd
import shlex
import shutil
import signal
import socket
import struct
import subprocess
import sys
import tempfile
import time
from typing import Any, Callable, Optional
import zlib


EDITOR_TEXT = "kokuban ssh café"
HOST_ALIAS = "kokuban-ci-host"
STEP_TIMEOUT = 12


def record(directory: Path, name: str, value: Any) -> None:
    """Publish complete observations; the observer never sees partial JSON."""
    temporary = directory / (name + ".pending")
    temporary.write_text(json.dumps(value), encoding="utf-8")
    temporary.replace(directory / name)


def run(args: list[str], **kwargs: Any) -> subprocess.CompletedProcess:
    kwargs.setdefault("timeout", STEP_TIMEOUT)
    kwargs.setdefault("check", True)
    kwargs.setdefault("capture_output", True)
    return subprocess.run(args, **kwargs)


def process_identity(pid: int) -> Optional[list[int]]:
    """Include Linux's start time so cleanup never signals a reused PID."""
    try:
        fields = Path(f"/proc/{pid}/stat").read_text().rpartition(")")[2].split()
        return [pid, int(fields[2]), int(fields[19])]
    except (OSError, ValueError, IndexError):
        return None


def remote_driver(directory: Path) -> None:
    """Run inside the SSH PTY; all interactive input arrives from the window."""
    os.chdir(directory)
    os.environ.update(LC_ALL="C.UTF-8", ENV="/dev/null", FZF_DEFAULT_OPTS="")
    os.environ.pop("FZF_DEFAULT_COMMAND", None)
    os.environ["FZF_DEFAULT_OPTS_FILE"] = "/dev/null"
    tty_size = lambda: list(os.get_terminal_size(0))
    if not all(os.isatty(fd) for fd in (0, 1, 2)):
        raise AssertionError("SSH did not allocate a controlling terminal")
    record(directory, "remote-process.json", process_identity(os.getpid()))
    signal.signal(
        signal.SIGWINCH,
        lambda _signal, _frame: record(directory, "remote-resize.json", tty_size()),
    )
    record(directory, "remote-ready.json", {
        "size": tty_size(), "term": os.environ.get("TERM"),
        "ssh_connection": os.environ.get("SSH_CONNECTION"),
    })
    print("\x1b[2J\x1b[HKOKUBAN SSH READY", flush=True)
    received = input()
    if received != "ssh-input-check":
        raise AssertionError(f"unexpected window input: {received!r}")
    record(directory, "input.json", received)
    if input() != "resize-ok":
        raise AssertionError("missing resize acknowledgement through the window")

    try:
        record(directory, "interrupt-ready.json", True)
        time.sleep(30)
    except KeyboardInterrupt:
        record(directory, "interrupted.json", True)
    else:
        raise AssertionError("Ctrl-C did not interrupt the remote foreground program")

    # VimEnter and TextChangedI are application observations, not timer guesses.
    init = directory / "nvim-init.vim"
    init.write_text(
        "set encoding=utf-8 noswapfile nobackup nowritebackup\n"
        "set termguicolors\n"
        "autocmd VimEnter * call writefile(['ready'], 'nvim-ready')\n"
        "autocmd TextChangedI * call writefile([getline(1)], 'nvim-inserted')\n",
        encoding="utf-8",
    )
    subprocess.run(
        ["nvim", "-u", str(init), "-i", "NONE", "editor.txt"],
        check=True, timeout=30,
    )
    if (directory / "editor.txt").read_text(encoding="utf-8") != EDITOR_TEXT + "\n":
        raise AssertionError("Neovim did not save the text typed through SSH")
    record(directory, "nvim-done.json", True)

    with (directory / "fzf-result").open("wb") as result:
        subprocess.run(
            ["fzf", "--sync", "--no-multi", "--bind",
             "start:execute-silent(touch fzf-ready)"],
            input=b"alpha\nbeta\ngamma\n", stdout=result, check=True, timeout=30,
        )
    if (directory / "fzf-result").read_bytes() != b"beta\n":
        raise AssertionError("fzf did not select beta from window keyboard input")
    record(directory, "fzf-done.json", True)

    subprocess.run(
        ["tmux", "-S", str(directory / "tmux.sock"), "-f", "/dev/null",
         "new-session", "-s", "smoke", "/bin/sh -i"],
        check=True, timeout=35,
    )
    if (directory / "tmux-result").read_bytes() != b"KOKUBAN_TMUX_OK\n":
        raise AssertionError("the tmux split did not execute window input")
    print("\r\nKOKUBAN SSH APPS COMPLETE", flush=True)
    record(directory, "session-result.json", {"ok": True})


def stop_process(process: Optional[subprocess.Popen]) -> None:
    if process is None or process.poll() is not None:
        return
    process.terminate()
    try:
        process.wait(timeout=4)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait(timeout=4)


def stop_remote_group(directory: Path) -> None:
    """End the fixture's SSH foreground group, including any failed TUI."""
    identity = read_json(directory / "remote-process.json")
    if not identity or process_identity(identity[0]) != identity:
        return
    group = identity[1]
    if group <= 1 or group == os.getpgrp():
        raise AssertionError("refusing to signal a non-isolated remote process group")
    for signum in (signal.SIGTERM, signal.SIGKILL):
        if process_identity(identity[0]) != identity:
            return
        try:
            os.killpg(group, signum)
        except ProcessLookupError:
            return
        if signum == signal.SIGTERM:
            deadline = time.monotonic() + 2
            while time.monotonic() < deadline:
                if process_identity(identity[0]) != identity:
                    return
                time.sleep(0.05)


def wait_for(
    description: str,
    observe: Callable[[], Any],
    processes: tuple[subprocess.Popen, ...],
    timeout: float = STEP_TIMEOUT,
) -> Any:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        result = observe()
        if result:
            return result
        for process in processes:
            if process.poll() is not None:
                raise AssertionError(
                    f"{description}: process {process.pid} exited {process.returncode}"
                )
        time.sleep(0.05)
    raise AssertionError(f"timed out waiting for {description}")


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else None


def ssh_arguments(directory: Path, port: int, known_hosts: Path) -> list[str]:
    return [
        "ssh", "-F", "/dev/null", "-p", str(port), "-i", str(directory / "client"),
        "-o", "BatchMode=yes", "-o", "IdentitiesOnly=yes",
        "-o", "IdentityAgent=none", "-o", "StrictHostKeyChecking=yes",
        "-o", f"UserKnownHostsFile={known_hosts}",
        "-o", "GlobalKnownHostsFile=/dev/null", "-o", f"HostKeyAlias={HOST_ALIAS}",
        "-o", "UpdateHostKeys=no", "-o", "VerifyHostKeyDNS=no",
        "-o", "ConnectTimeout=5", "-o", "ConnectionAttempts=1",
        "-o", "ServerAliveInterval=5", "-o", "ServerAliveCountMax=2",
        "-l", pwd.getpwuid(os.getuid()).pw_name,
    ]


def prepare_server(directory: Path) -> tuple[Path, int]:
    for name in ("host", "wrong-host", "client"):
        run(["ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-f", str(directory / name)])
    authorized = directory / "authorized_keys"
    authorized.write_bytes((directory / "client.pub").read_bytes())
    authorized.chmod(0o600)
    for name, host in (("known_hosts", "host"), ("wrong_known_hosts", "wrong-host")):
        public_key = (directory / (host + ".pub")).read_text().split()
        (directory / name).write_text(f"{HOST_ALIAS} {public_key[0]} {public_key[1]}\n")
    with socket.socket() as reservation:
        reservation.bind(("127.0.0.1", 0))
        port = reservation.getsockname()[1]
    config = directory / "sshd_config"
    config.write_text(
        f"Port {port}\nListenAddress 127.0.0.1\nAddressFamily inet\n"
        f"HostKey {directory / 'host'}\nPidFile {directory / 'sshd.pid'}\n"
        f"AuthorizedKeysFile {authorized}\n"
        f"AllowUsers {pwd.getpwuid(os.getuid()).pw_name}\n"
        "AuthenticationMethods publickey\nPubkeyAuthentication yes\n"
        "PasswordAuthentication no\nKbdInteractiveAuthentication no\nUsePAM no\n"
        "StrictModes yes\nPermitTTY yes\nDisableForwarding yes\n"
        "PermitUserRC no\nPermitUserEnvironment no\n"
        "PrintMotd no\nPrintLastLog no\nUseDNS no\nLogLevel VERBOSE\n"
    )
    return config, port


def server_listening(port: int) -> bool:
    try:
        with socket.create_connection(("127.0.0.1", port), timeout=0.2):
            return True
    except OSError:
        return False


def find_window(process: subprocess.Popen) -> Optional[str]:
    result = run(
        ["xdotool", "search", "--onlyvisible", "--pid", str(process.pid)], check=False
    )
    windows = result.stdout.decode().split()
    return windows[0] if result.returncode == 0 and windows else None


def key(*keys: str) -> None:
    # Omitting --window uses XTest, which follows winit's real keyboard path.
    run(["xdotool", "key", "--clearmodifiers", "--delay", "40", *keys])


def type_text(text: str) -> None:
    result = run(["xdotool", "type", "--clearmodifiers", "--delay", "15", "--", text])
    if result.stderr:
        print("XTest typing: " + result.stderr.decode(errors="replace"), file=sys.stderr)


def screenshot(window: str, destination: Path) -> None:
    """Convert the Xvfb TrueColor XWD to PNG using only the standard library."""
    data = run(["xwd", "-id", window, "-silent"]).stdout
    if len(data) < 100:
        raise AssertionError("truncated XWD screenshot")
    header = struct.unpack_from(">25I", data)
    size, version, image_format, _, width, height, xoffset, byte_order = header[:8]
    bits, stride, visual = header[11:14]
    masks = header[14:17]
    offset = size + header[19] * 12
    if (version != 7 or image_format != 2 or visual != 4 or xoffset != 0
            or bits not in (24, 32) or byte_order not in (0, 1)
            or not all(masks) or stride < width * (bits // 8)
            or len(data) < offset + stride * height):
        raise AssertionError("expected a complete Xvfb TrueColor XWD")
    channels = [(mask, (mask & -mask).bit_length() - 1) for mask in masks]
    pixels = bytearray()
    order = "little" if byte_order == 0 else "big"
    for row in range(height):
        pixels.append(0)
        for column in range(width):
            start = offset + row * stride + column * (bits // 8)
            pixel = int.from_bytes(data[start:start + bits // 8], order)
            for mask, shift in channels:
                pixels.append(((pixel & mask) >> shift) * 255 // (mask >> shift))

    def chunk(kind: bytes, content: bytes) -> bytes:
        return (struct.pack(">I", len(content)) + kind + content
                + struct.pack(">I", zlib.crc32(kind + content)))

    destination.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">2I5B", width, height, 8, 2, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(pixels)) + chunk(b"IEND", b"")
    )


def tmux_panes(directory: Path) -> list[str]:
    result = run(
        ["tmux", "-S", str(directory / "tmux.sock"), "list-panes",
         "-t", "smoke", "-F", "#{pane_id} #{pane_width} #{pane_height}"],
        check=False,
    )
    return result.stdout.decode().splitlines() if result.returncode == 0 else []


def expected_tmux_panes(directory: Path, count: int) -> Optional[list[str]]:
    panes = tmux_panes(directory)
    return panes if len(panes) == count else None


def exercise_window(directory: Path, port: int, binary: Path, daemon: subprocess.Popen) -> None:
    command = ssh_arguments(directory, port, directory / "known_hosts")
    remote = shlex.join([sys.executable, str(Path(__file__).resolve()), "--remote-dir", str(directory)])
    shell = directory / "shell"
    shell.write_text(
        "#!/bin/sh\n" + shlex.join(command + ["-tt", "127.0.0.1", remote])
        + "\nstatus=$?\nprintf '%s' \"$status\" > ssh-exit\nexit \"$status\"\n"
    )
    shell.chmod(0o700)
    (directory / "kokuban.toml").write_text(
        '[font]\nfamily = "DejaVu Sans Mono"\nsize = 14.0\n'
        '[window]\ncolumns = 80\nrows = 24\n'
    )
    environment = os.environ.copy()
    for name in ("WAYLAND_DISPLAY", "WAYLAND_SOCKET", "XDG_RUNTIME_DIR", "KOKUBAN_EXIT_AFTER_FIRST_FRAME"):
        environment.pop(name, None)
    environment.update(KOKUBAN_SHELL=str(shell), WINIT_X11_SCALE_FACTOR="1", LC_ALL="C.UTF-8")
    with (directory / "terminal.log").open("wb") as log:
        terminal = subprocess.Popen([str(binary)], cwd=directory, env=environment, stdout=log, stderr=log)
        processes = (daemon, terminal)
        window = None
        try:
            window = wait_for("Linux window", lambda: find_window(terminal), processes)
            run(["xdotool", "windowfocus", "--sync", window])
            ready = wait_for("remote SSH PTY", lambda: read_json(directory / "remote-ready.json"), processes)
            if ready["term"] != "xterm-256color" or not ready["ssh_connection"]:
                raise AssertionError(f"incorrect remote terminal environment: {ready}")
            if ready["size"] != [80, 24]:
                raise AssertionError(f"incorrect initial remote size: {ready['size']}")
            type_text("ssh-input-check")
            key("Return")
            wait_for("remote keyboard input", lambda: read_json(directory / "input.json"), processes)

            geometry = run(["xdotool", "getwindowgeometry", "--shell", window]).stdout.decode()
            dimensions = dict(line.split("=", 1) for line in geometry.splitlines() if "=" in line)
            width, height = int(dimensions["WIDTH"]), int(dimensions["HEIGHT"])
            if width % 80 or height % 24:
                raise AssertionError(f"initial Linux window is not cell-aligned: {width}x{height}")
            run(["xdotool", "windowsize", "--sync", window,
                 str(width + width // 80 * 8), str(height + height // 24 * 3)])
            wait_for(
                "remote SIGWINCH and 88x27 PTY",
                lambda: read_json(directory / "remote-resize.json") == [88, 27],
                processes,
            )
            type_text("resize-ok")
            key("Return")
            wait_for(
                "remote interrupt test",
                lambda: read_json(directory / "interrupt-ready.json"), processes,
            )
            key("ctrl+c")
            wait_for("remote Ctrl-C", lambda: read_json(directory / "interrupted.json"), processes)

            wait_for("Neovim UI", lambda: (directory / "nvim-ready").exists(), processes)
            type_text("i" + EDITOR_TEXT)
            inserted = directory / "nvim-inserted"
            wait_for(
                "Neovim Unicode insertion",
                lambda: inserted.exists()
                and inserted.read_text(encoding="utf-8") == EDITOR_TEXT + "\n",
                processes,
            )
            screenshot(window, directory / "neovim.png")
            key("Escape")
            type_text(":wq")
            key("Return")
            wait_for("saved Neovim file", lambda: read_json(directory / "nvim-done.json"), processes)

            wait_for("fzf UI", lambda: (directory / "fzf-ready").exists(), processes)
            type_text("beta")
            screenshot(window, directory / "fzf.png")
            key("Return")
            wait_for("fzf selection", lambda: read_json(directory / "fzf-done.json"), processes)

            wait_for("attached tmux", lambda: len(tmux_panes(directory)) == 1, processes)
            key("ctrl+b")
            type_text("%")
            panes = wait_for(
                "tmux keyboard split", lambda: expected_tmux_panes(directory, 2),
                processes,
            )
            record(directory, "tmux-panes.json", panes)
            type_text("printf 'KOKUBAN_TMUX_OK\\n' > " + shlex.quote(str(directory / "tmux-result")))
            key("Return")
            wait_for("tmux pane command", lambda: (directory / "tmux-result").exists()
                     and (directory / "tmux-result").read_bytes() == b"KOKUBAN_TMUX_OK\n", processes)
            screenshot(window, directory / "tmux.png")
            type_text("exit")
            key("Return")
            wait_for("first tmux pane exit", lambda: len(tmux_panes(directory)) == 1, processes)
            type_text("exit")
            key("Return")
            wait_for(
                "remote session completion",
                lambda: read_json(directory / "session-result.json"), processes,
            )
            terminal.wait(timeout=STEP_TIMEOUT)
            if terminal.returncode != 0 or (directory / "ssh-exit").read_text() != "0":
                raise AssertionError("SSH or the Linux terminal did not disconnect cleanly")
        except BaseException:
            inserted = directory / "nvim-inserted"
            if inserted.exists():
                print(f"Observed Neovim text: {inserted.read_bytes()!r}", file=sys.stderr)
            if window:
                try:
                    screenshot(window, directory / "failure.png")
                except (OSError, ValueError, subprocess.SubprocessError) as error:
                    print(f"Could not capture failed application: {error}", file=sys.stderr)
            raise
        finally:
            try:
                run(["tmux", "-S", str(directory / "tmux.sock"), "kill-server"], check=False)
            finally:
                try:
                    stop_remote_group(directory)
                finally:
                    stop_process(terminal)


def check(binary: Path, artifacts: Optional[Path]) -> None:
    if sys.platform != "linux" or os.geteuid() == 0:
        raise SystemExit("run this fixture as an ordinary Linux user under Xvfb")
    required = ("ssh", "ssh-keygen", "sshd", "xdotool", "xwd", "nvim", "fzf", "tmux")
    missing = [name for name in required if shutil.which(name) is None]
    if missing:
        raise SystemExit("missing test programs: " + ", ".join(missing))
    if artifacts:
        artifacts.mkdir(parents=True, exist_ok=True)
    # StrictModes validates authorized_keys ancestors. A private directory
    # beneath the account's home avoids the world-writable /tmp ancestor.
    with tempfile.TemporaryDirectory(prefix="kokuban-apps-", dir=Path.home()) as temporary:
        directory = Path(temporary)
        daemon = None
        try:
            versions = {}
            for name, arguments in (
                ("neovim", ["nvim", "--version"]),
                ("fzf", ["fzf", "--version"]),
                ("tmux", ["tmux", "-V"]),
            ):
                result = run(arguments, check=False)
                versions[name] = result.stdout.decode(errors="replace").splitlines()[:1]
            versions["ssh"] = run(["ssh", "-V"], check=False).stderr.decode().splitlines()[:1]
            record(directory, "versions.json", versions)
            config, port = prepare_server(directory)
            executable = str(Path(shutil.which("sshd")).resolve())
            run([executable, "-t", "-f", str(config)])
            with (directory / "sshd.log").open("wb") as log:
                daemon = subprocess.Popen([executable, "-D", "-e", "-f", str(config)], stdout=log, stderr=log)
                wait_for("loopback sshd", lambda: server_listening(port), (daemon,))
                rejected = run(
                    ssh_arguments(directory, port, directory / "wrong_known_hosts")
                    + ["127.0.0.1", "touch " + shlex.quote(str(directory / "wrong-host-executed"))],
                    check=False,
                )
                (directory / "host-key-rejection.log").write_bytes(rejected.stderr)
                if (rejected.returncode != 255 or b"Host key verification failed" not in rejected.stderr
                        or (directory / "wrong-host-executed").exists()):
                    raise AssertionError("the deliberately wrong pinned host key was not rejected")
                exercise_window(directory, port, binary, daemon)
            print(
                "PASS Linux SSH: wrong host key rejected; pinned-key authentication; "
                "window input; remote PTY resize; Ctrl-C; Neovim Unicode save; "
                "fzf beta; tmux split; clean disconnect",
                flush=True,
            )
        except Exception:
            for name in ("host-key-rejection.log", "terminal.log", "sshd.log"):
                path = directory / name
                if path.exists():
                    print(f"{name}:\n{path.read_text(errors='replace')[-6000:]}", file=sys.stderr)
            raise
        finally:
            stop_process(daemon)
            # Deliberately enumerate safe outputs: never copy keys or the whole fixture.
            if artifacts:
                for name in ("terminal.log", "sshd.log", "host-key-rejection.log", "versions.json",
                             "remote-ready.json", "remote-resize.json", "input.json", "interrupted.json",
                             "tmux-panes.json", "session-result.json", "editor.txt", "fzf-result", "tmux-result",
                             "neovim.png", "fzf.png", "tmux.png", "failure.png", "nvim-ready", "nvim-inserted"):
                    if (directory / name).is_file():
                        shutil.copyfile(directory / name, artifacts / name)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("binary", type=Path, nargs="?")
    parser.add_argument("--artifacts-dir", type=Path)
    parser.add_argument("--remote-dir", type=Path, help=argparse.SUPPRESS)
    args = parser.parse_args()
    if args.remote_dir:
        remote_driver(args.remote_dir.resolve(strict=True))
        return
    if args.binary is None:
        parser.error("provide the Kokuban binary to test")

    def interrupted(_signal: int, _frame: Any) -> None:
        raise TimeoutError("Linux application smoke interrupted or exceeded 150 seconds")

    signal.signal(signal.SIGTERM, interrupted)
    signal.signal(signal.SIGALRM, interrupted)
    signal.alarm(150)
    try:
        check(args.binary.resolve(strict=True), args.artifacts_dir)
    finally:
        signal.alarm(0)


if __name__ == "__main__":
    main()
